ANALYST_IDENTITY = "ANALYST"

SOAR_ASSISTANT_IDENTITY = "SOAR_ASSISTANT"
THREAT_INTEL_IDENTITY = "THREAT_INTEL_ENGINE"
UFW_AUTOMATION_IDENTITY = "UFW_AUTOMATION"
PLAYBOOK_ENGINE_IDENTITY = "PLAYBOOK_ENGINE"
AUTOMATED_INGESTION_IDENTITY = "AUTOMATED_INGESTION"

VALID_INCIDENT_STATUSES = {
    "OPEN",
    "INVESTIGATING",
    "CONTAINED",
    "CLOSED",
}

VALID_SEVERITIES = {
    "CRITICAL",
    "HIGH",
    "MEDIUM",
    "LOW",
    "INFORMATIONAL",
}
